declare module FinancialPlanning
{
    module Users
    {
        interface IUser
        {
            _id: string;

            hash: string;

            salt: string;
        }
    }

    module Transactions
    {
        interface ITransactionType
        {
            /**
             * Generated by mongodb
             */
            _id?: string;

            /**
             * Whether the transaction is incoming or outgoing
             */
            paymentDirection: string;

            name: string;

            classification: string;

            subClassification: string;

            /**
             * If this transaction type 'belongs' to a specific user, this must be included. It will stop it being displayed as
             * an option for other users
             */
            user?: string;
        }

        interface ITransaction
        {
            /**
             * Generated by mongodb
             */
            _id?: string;

            /**
             * Link to unique user _id
             */
            user: string;

            amount: number;

        }
    }

    module Security
    {
        interface IPasswordHash
        {
            hash: string;

            salt: string;
        }
    }
}